#!/bin/bash
#
# The 'run' performs a simple test that verifies the image.

source $(readlink -zf $(dirname "${BASH_SOURCE[0]}"))/functions

run_docker_app() {
  CONTAINER_ARGS=${CONTAINER_ARGS:-'--user=100001'}
  docker run ${CONTAINER_ARGS} --rm --cidfile=${cid_file} ${IMAGE_NAME} &>/dev/null
}

test_port() {
  info "Checking the container port $(container_ip) $(container_port) is open.."
  if hash nc 2>/dev/null; then
      return $(nc -z $(container_ip) $(container_port))
  else
    info "WARNING: nc command not available on test host"
    return 0
  fi
}

test_component() {
  local cid_file=$(mktemp -u --suffix=.cid)
  run_docker_app &

  # Wait for the container to write it's CID file
  wait_for_cid

  test_image_version "${VERSION_COMMAND}" "${VERSION}" "${cid_file}"
  check_result $?

  test_port
  check_result $?

  # Extra tests
  if [ -n "$(type extra_tests)" ]; then
    extra_tests
  fi

  cleanup_container
}

test_component

info "All tests finished successfully."
